Add error handling to kakoune startup script

diff --git a/bin/kak b/bin/kak
--- a/bin/kak
+++ b/bin/kak
@@ -1,4 +1,10 @@
 #!/bin/sh
+set -eu
+
+command -v kak >/dev/null 2>&1 || {
+    echo >&2 "Kakoune is not installed. Aborting."
+    exit 1
+}
 
 socket_file=$(kak -l | grep $USER)
 
